README.md, pybleau/app/model/dataframe_analyzer.py, pybleau/app/ui/dataframe_analyzer_model_view.py
Make and document that Chaco, seaborn matplotlib are now an optional packages.
=> Make multiple packages optional. Support but warn about pandas < 0.20.

pybleau/app/ui/dataframe_plot_manager_view.py, pybleau/app/ui/tests/test_dataframe_plot_manager_model_view.py
Add the ability to control the list and order of the columns displayed in the plot control table.
=> Customize plot control table

pybleau/app/plotting/plot_style.py
Argh, #9 was missing this commit!
=> Improve style UI.

pybleau/app/api.py, pybleau/app/app/main.py, pybleau/app/app/tests/test_main.py, pybleau/app/main.py, pybleau/utils/pandas_utils.py, scripts/explore_dataframe.py, scripts/explore_dataframe_with_plots.py
Add a main function to launch the DataframeAnalyzer as a standalone app or pop up tool.
=> Feature: add app entry point

pybleau/app/io/deserializer.py, pybleau/app/io/serializer.py, pybleau/app/io/tests/test_plot_styles_roundtrip.py, pybleau/app/io/tests/test_plotting_roundtrip.py, pybleau/app/io/tests/test_renderer_styles_serialization.py, pybleau/app/model/dataframe_plot_manager.py, pybleau/app/model/plot_descriptor.py, pybleau/app/plotting/axis_style.py, pybleau/app/plotting/bar_factory.py, pybleau/app/plotting/bar_plot_style.py, pybleau/app/plotting/contour_style.py, pybleau/app/plotting/heatmap_plot_style.py, pybleau/app/plotting/histogram_factory.py, pybleau/app/plotting/histogram_plot_style.py, pybleau/app/plotting/plot_config.py, pybleau/app/plotting/plot_style.py, pybleau/app/plotting/renderer_style.py, pybleau/app/plotting/tests/test_dataframe_plot_factories.py, pybleau/app/plotting/tests/test_plot_config.py, pybleau/app/plotting/tests/test_plot_styles.py, pybleau/app/plotting/tests/test_renderer_styles.py, pybleau/app/plotting/title_style.py, pybleau/app/ui/branding.py, pybleau/app/utils/string_definitions.py
Serialization wasn't tested in this repo, and testing was left for downstream projects if they decided to reuse the (de)serializers in this project. This PR changes that by adding functional entry points for this project, and extensive unit tests
It also continues the rationalization of the plot styles, and division of responsibilities started in #20 .
=> More plot styles improvements and many serialization fixes

pybleau/app/plotting/base_factories.py, pybleau/app/plotting/multi_plot_config.py, pybleau/app/plotting/plot_config.py, pybleau/app/plotting/plot_factories.py, pybleau/app/plotting/tests/test_dataframe_plot_factories.py, pybleau/app/plotting/tests/test_multi_plot_config.py, pybleau/app/utils/string_definitions.py
First benefit of the work done in #20 : we can now support creating plots with multiple renderers (with controls for each)! 
This PR expands the multi-line plot capability to support having all curves inside a single plot (default).
=> Feature: support multi-curve plots

pybleau/app/io/legacy_deserializer.py, pybleau/app/model/dataframe_plot_manager.py, pybleau/app/model/tests/test_dataframe_plot_manager.py, pybleau/app/plotting/base_factories.py, pybleau/app/plotting/scatter_factories.py, pybleau/app/ui/dataframe_plot_manager_view.py
All plot and axis title updates broken. This PR fixes them.
=> Fix plot title updates

pybleau/__init__.py, pybleau/app/model/tests/test_dataframe_plot_manager.py, pybleau/app/plotting/base_factories.py, pybleau/app/plotting/heatmap_factory.py, pybleau/app/plotting/scatter_factories.py
Unify colorbar generation between heatmap and cmap scatter.
Accidentally included here the commit a3404ba which was intended for #37 .
=> Enh: better colorbar handling

pybleau/app/api.py, pybleau/app/plotting/base_factories.py, pybleau/app/plotting/plot_style.py, pybleau/app/plotting/tests/test_plot_styles.py
... in the plot style view. Previous implementation would fail on python2.
=> Fix the ordering and naming of the renderer styles

pybleau/app/model/dataframe_plot_manager.py, pybleau/app/plotting/base_factories.py, pybleau/app/plotting/plot_context_menu_manager.py, pybleau/app/plotting/scatter_factories.py, pybleau/app/plotting/tests/test_dataframe_plot_factories.py, scripts/explore_dataframe_with_plots.py
New quick access for common functionalities:
- edit style
- export to file
- delete plot
Proof of concept to try out an architecture for handling this.
Also includes fly-by small improvements to the DFPlotManager around initialization and plot updates.
=> Feature: add plot tools via context menu

pybleau/app/plotting/base_factories.py
=> Fix angle of the title of the colorbars.

pybleau/app/plotting/plot_config.py
More tests for this coming in separate PR.
=> Don't overwrite config's style unless necessary.

pybleau/app/io/deserializer.py, pybleau/app/io/serializer.py, pybleau/app/io/tests/test_analyzer_roundtrip.py, pybleau/app/io/tests/test_plotting_roundtrip.py, pybleau/app/plotting/plot_config.py
- Add serialization and deserialization of a `DataframeAnalyzer`, not just a `DataFramePlotManager`.
- Add many serialization tests, including serialization of analyzers containing styled plots.
=> Feature: analyzer serialization

pybleau/app/io/tests/test_analyzer_roundtrip.py, pybleau/app/model/dataframe_plot_manager.py
- Update tests for new app_common's `ConstraintsPlotContainerManager` to fix overlaid axes/labels. 
- Rename method.
- Fixes #57
=> Update to newest app_common

pybleau/app/plotting/bar_plot_style.py, pybleau/app/plotting/heatmap_plot_style.py, pybleau/app/plotting/histogram_plot_style.py, pybleau/app/plotting/plot_style.py, pybleau/app/plotting/tests/test_dataframe_plot_factories.py, pybleau/app/plotting/tests/test_plot_styles.py
- Make the renderer_styles panel scrollable. 
- Update tests since model has to change.
=> Better handling styling of many renderers

pybleau/app/plotting/base_factories.py, pybleau/app/plotting/scatter_factories.py
=> Use styling to set axes to log or linear scale.

pybleau/app/ui/dataframe_analyzer_model_view.py
This fixes one of the issues that leads to hard Qt5 crashes when using the column list editor in the DFAnalyzer. The other issue is fixed in https://github.com/enthought/traitsui/pull/897 .
=> Feature: summary column control

pybleau/app/ui/dataframe_analyzer_model_view.py
Also tweak button label since left arrow is confusing.
Fixes #84 .
=> Fix trying to open the popup multiple times.

.coveragerc, .travis.yml, MANIFEST.in, etstool.py, install-edm-linux.sh, install-edm-osx.sh, setup.py
Add continuous integration via travis CI since it's free for this package.
=> Initial upload of travis ci files.

ci/requirements.json, pybleau/app/io/plot_io_utils.py, pybleau/app/io/serializer.py, pybleau/app/io/tests/test_analyzer_roundtrip.py, pybleau/app/io/tests/test_dataframe_plot_manager_exporter.py, pybleau/app/io/tests/test_plotting_roundtrip.py, pybleau/app/model/dataframe_plot_manager.py, pybleau/app/model/plot_descriptor.py, pybleau/app/model/tests/test_dataframe_plot_manager.py, pybleau/app/plotting/api.py, pybleau/app/plotting/i_plot_template_interactor.py, pybleau/app/plotting/interface_plot_template_interactor.py, pybleau/app/plotting/plot_config.py, pybleau/app/plotting/plot_context_menu_manager.py, pybleau/app/plotting/template_plot_selector.py, pybleau/app/plotting/tests/test_plot_styles.py, pybleau/app/plotting/tests/test_template_plot_selector.py, pybleau/app/ui/dataframe_plot_manager_view.py, pybleau/app/ui/tests/test_dataframe_plot_manager_model_view.py, scripts/explore_dataframe_with_plots.py
=> Add the ability to create custom plot templates from existing plots

.circleci/config.yml, etstool.py, install-edm-windows.cmd
Add CircleCI based continuous integration for Windows.
=> Windows CI with circleCI

pybleau/app/ui/dataframe_analyzer_model_view.py, pybleau/app/ui/tests/test_dataframe_analyzer_model_view.py
Change the behavior of the categorical summary such that a flag controls whether it is visible or not.
=> Change categorical summary

pybleau/app/model/multi_dfs_dataframe_analyzer.py, pybleau/app/model/tests/base_dataframe_analyzer.py, pybleau/app/model/tests/test_multi_df_dataframe_analyzer.py
Add new public methods to modify a column or a value of the source_df without having to access private attributes.
=> Add new public API for multi-df analyzer.

pybleau/app/model/dataframe_plot_manager.py, pybleau/app/model/tests/test_dataframe_plot_manager.py, pybleau/app/ui/dataframe_plot_manager_view.py
Fixes #120 
xref: KBIbiopharma/particle_data_viewer/issues/702
=> Fix axes ranges of custom plot templates and saved plots that are not preserved

pybleau/app/ui/dataframe_analyzer_model_view.py
Add more recording of pybleau actions to support usage analysis.
=> Add more logging calls to track actions inside DFAnalyzer.

pybleau/app/model/plot_template_manager.py, pybleau/app/model/tests/test_plot_template_manager.py
=> Fix failing test for PlotTemplateManager

pybleau/app/utils/chaco_colors.py
Adding more default colors to the `BASIC_COLORS` list.
=> Add more default colors to BASIC_COLORS

pybleau/app/io/tests/test_plot_styles_roundtrip.py, pybleau/app/plotting/multi_plot_config.py, pybleau/app/plotting/plot_config.py, pybleau/app/plotting/plot_style.py, pybleau/app/plotting/tests/test_dataframe_plot_factories.py, pybleau/app/utils/chaco_colors.py, pybleau/app/utils/tests/test_chaco_colors.py
Fixes KBIbiopharma/particle_data_viewer/issues/726
=> Deserialized plots from project files and from templates do not preserve colors

pybleau/app/io/deserializer.py, pybleau/app/io/serializer.py, pybleau/app/io/tests/test_analyzer_roundtrip.py
Add serialization tools for the new MultiDFAnalyzer class.
=> Feature: MultiDfAnalyzer (de)serializer

etstool.py
Improve their handling for future.
=> Remove pyside2 and wx from supported list

pybleau/app/model/multi_dfs_dataframe_analyzer.py
Clarify that that attribute is internal and not supposed to be provided at creation.
=> Enh: make multi df analyzer column_loc attribute private

pybleau/app/io/serializer.py, pybleau/app/io/tests/test_analyzer_roundtrip.py, pybleau/app/model/dataframe_analyzer.py, pybleau/app/model/tests/base_dataframe_analyzer.py, pybleau/app/model/tests/test_dataframe_analyzer.py, pybleau/app/model/tests/test_multi_df_dataframe_analyzer.py
Renaming to make it clearer that one can store anything in this new dictionary.
=> Rename column_descr to column_metadata

pybleau/app/io/dataframe_plot_manager_exporter.py
I believe this fixes https://github.com/KBIbiopharma/particle_data_viewer/issues/750.
=> Fix plot export failure

pybleau/app/model/multi_dfs_dataframe_analyzer.py
Add requested comment in review of https://github.com/KBIbiopharma/pybleau/pull/163 .
=> Add missing comment.

pybleau/app/plotting/multi_plot_config.py, pybleau/app/plotting/plot_config.py, pybleau/app/plotting/tests/test_plot_config.py, pybleau_plotting.puml
xref: https://github.com/KBIbiopharma/particle_data_viewer/issues/772
=> Removed non-numerical columns from x/y axes selections

pybleau/app/model/dataframe_analyzer.py, pybleau/app/plotting/plot_config.py
This will move the boolean values to the categorical summary rather than the numerical one as done for the `Handled` column in this screenshot:
=> Handle boolean value as a categorical column.

pybleau/app/image_resources.py, pybleau/app/ui/dataframe_analyzer_model_view.py, pybleau/app/ui/filter_expression_editor.py, pybleau/app/ui/tests/test_dataframe_analyzer_model_view.py, pybleau/app/ui/tests/test_filter_expression_editor.py, pybleau/app/utils/scrollable_button_list_view.py
Resolves https://github.com/KBIbiopharma/particle_data_viewer/issues/685
=> Allow users to pop-out a filter expression editor with copy/append functionality

pybleau/app/plotting/plot_config.py, pybleau/app/plotting/tests/test_plot_config.py
=> Fix missing columns in available plot selections

setup.py
Followed example in other repos. Please correct if not right.
=> Add app images to setup.py

pybleau/app/model/multi_dfs_dataframe_analyzer.py, pybleau/app/model/tests/test_multi_df_dataframe_analyzer.py
- Update `_source_df_columns` when new columns are added.
- Add getters for entries in `_source_dfs` and `_source_df_columns`
- Misc improvements to the code
=> Mutli-df analyzer improvements

etstool.py
=> Maint: improve ets tools

pybleau/app/plotting/base_factories.py, pybleau/app/plotting/heatmap_factory.py, pybleau/app/plotting/tests/test_dataframe_plot_factories.py
=> Enh: heatmap label positions

pybleau/app/model/multi_dfs_dataframe_analyzer.py, pybleau/app/model/tests/test_multi_df_dataframe_analyzer.py
Note: merging this will require an update to downstream projects since by default, this method didn't trigger a notification and it now will.
=> Enh: set source df val update triggers a notification
