pybleau/app/ui/dataframe_analyzer_model_view.py

Add controls to display the shuffle button and the button to show/hide the summary table. This allows to have a more minimal version of the DF viewer where no analysis is needed.

More granular controls to build a simple DF viewer.

---

pybleau/app/ui/dataframe_plot_manager_view.py

Now that there is a `Move/Delete` column to control the location of the plots in the plot canvas, this turns off both deletable and reorderable on plot control table so users can't modify the list that way and there is only 1 way to do something. 2 reasons:
- The context menu could put users in a broken state due to a complex interaction between the MultiCanvas object and the list of descriptors.
- Additionally, some bug in TraitsUI's `SplitEditorAreaPane` would sometimes highjack the context menu events.
- Removing these operations also simplifies the view, because it hides the additional index which was redundant with our own ID column.

Remove context menu on plot control table

---

pybleau/app/plotting/base_factories.py
pybleau/app/plotting/plot_style.py
pybleau/app/plotting/tests/test_dataframe_plot_factories.py
scripts/explore_dataframe_with_plots.py

When building bar plots with a string index, we may not want to apply the normal chaco tick decimation algorithm. Add a check box in the styling UI to force the display of all values.

Enh: control if string axis labels can be decimated

---

pybleau/app/plotting/plot_style.py

#9 introduced a syntax error on Python2 only. This fixes it so both versions of Python are still supported.

Fix Python 2 syntax error

---

pybleau/app/plotting/plot_style.py

Style initialization: support providing the mapper if not using a `chaco.Plot`.

Support providing specific mappers when not using a chaco.Plot

---

pybleau/app/io/deserializer.py
pybleau/app/io/serializer.py
pybleau/app/io/tests/test_plot_styles_roundtrip.py
pybleau/app/io/tests/test_plotting_roundtrip.py
pybleau/app/model/dataframe_plot_manager.py
pybleau/app/model/plot_descriptor.py
pybleau/app/model/tests/test_dataframe_plot_manager.py
pybleau/app/plotting/axis_style.py
pybleau/app/plotting/bar_factory.py
pybleau/app/plotting/base_factories.py
pybleau/app/plotting/heatmap_factory.py
pybleau/app/plotting/heatmap_plot_style.py
pybleau/app/plotting/histogram_factory.py
pybleau/app/plotting/line_factory.py
pybleau/app/plotting/multi_plot_config.py
pybleau/app/plotting/plot_config.py
pybleau/app/plotting/plot_container_style.py
pybleau/app/plotting/plot_style.py
pybleau/app/plotting/renderer_style.py
pybleau/app/plotting/scatter_factories.py
pybleau/app/plotting/tests/test_dataframe_plot_factories.py
pybleau/app/plotting/tests/test_plot_styles.py
pybleau/app/ui/dataframe_plot_manager_view.py
scripts/explore_dataframe_with_plots.py

* Move implementation of all factories from `Plot` to `OverlayPlotContainer`.
* Add renderer styling so plot styling can offer a lot more granular control over styling including color
* Supports moving XY plots from the left y-axis to a secondary one on the right.
* Global code improvements to increase code reuse, remove dead attributes, ...
Requires `app_common` version `0.13.0` or above.

Move architecture from Plot to OverlayPlotContainer

---

pybleau/app/io/deserializer.py
pybleau/app/io/legacy_deserializer.py
pybleau/app/io/serializer.py

- Somehow, the removal of the `ndim` attribute of a PlotDescriptor in #33  didn't require a bump in the protocol version for the serializer/deserializer. This PR reverts that.
- Added a legacy deserializer module to be use to contribute to downstream projects serializing objects containing pybleau plot components.
- Add deserializer for the `BaseXYPlotStyle` since there is a serializer for it.

Maint: legacy descriptor serializer

---

pybleau/app/io/deserializer.py
pybleau/app/io/legacy_deserializer.py
pybleau/app/io/serializer.py

Update DFPlotter protocole to 1 and remove `next_plot_id` from list of serialized traits.

DFPlotter serialization: next_plot_id treated as the derived trait

---

pybleau/app/plotting/base_factories.py

Sadly, disabling that capability doesn't give the scroll event back to the parent window/widget.

Slow down mouse scroll for zooming. 

---

pybleau/app/io/deserializer.py
pybleau/app/io/legacy_deserializer.py
pybleau/app/io/serializer.py

Styles were organized differently: bump protocol numbers and handle legacy deserialization so styling information is lost (ok with only end users) but avoid deserialization failure.

Fix old style serialization

---

pybleau/app/plotting/plot_style.py

Fixing `Enum` syntax that doesn't work with Traits 6.1+.

Fix: traits bugs

---

pybleau/app/api.py
pybleau/app/model/multi_dfs_dataframe_analyzer.py
pybleau/app/model/tests/test_base_dataframe_analyzer.py
pybleau/app/model/tests/test_dataframe_analyzer.py
pybleau/app/model/tests/test_multi_df_dataframe_analyzer.py

Make a version of the `DFAnalyzer` that stores the source_df data in a list of dataframes rather than a single one. It is still designed to be used the same way as the base DFAnalyzer in most situations and the tests suite for the multi-df implementation a super set of the original implementation.

Feature: multi df analyzer

---

pybleau/app/api.py
pybleau/app/io/deserializer.py
pybleau/app/io/legacy_deserializer.py
pybleau/app/io/serializer.py
pybleau/app/model/dataframe_analyzer.py
pybleau/app/model/tests/test_base_dataframe_analyzer.py

This ensures that the analyzer's `index_name` and therefore the `sort_cols` options can't get out of sync with the `source_df` no matter the order of attribute assignment when building an Analyzer.

Enh: robustify df analyzer sort col

---

pybleau/app/model/dataframe_analyzer.py
pybleau/app/model/tests/base_dataframe_analyzer.py
pybleau/app/model/tests/test_dataframe_analyzer.py
pybleau/app/model/tests/test_multi_df_dataframe_analyzer.py

Refactor the sorting of the filtered_df so it can reused during the initialization of that attribute. Otherwise, the sorting isn't done right when requesting the descending order.
Unrelated: remove the check on the presence of the kiwisolver package since it is now available to all versions tested.

Fix: filtered df sorting

---

pybleau/__init__.py
pybleau/app/plotting/plot_container_style.py

Needed to avoid plot file export to be truncated.

Fix padding on plots so axes are not hidden when plots are exported to images

---

pybleau/app/plotting/axis_style.py
pybleau/app/plotting/base_factories.py
pybleau/app/plotting/plot_style.py
pybleau/app/plotting/tests/test_plot_styles.py
scripts/explore_dataframe_with_plots.py

Bring back text label controls for text x axis. Test by running the new `scripts/explore_dataframe_with_plots.py` and try editing the last bar plot on the first row:
Fixes #85

Fix: x axis finite labels controls

---

pybleau/app/model/dataframe_plot_manager.py
pybleau/app/model/tests/test_dataframe_plot_manager.py
pybleau/app/plotting/base_factories.py
pybleau/app/plotting/plot_style.py
pybleau/app/plotting/tests/test_plot_styles.py

Changing style's axis ranges currently only applied to the first renderer. This fixes that. Bug/fix can be reproduced/tested by running the example script scripts/explore_dataframe_with_plots.py and changing the an axis range on plot 3.
Unrelated: `plot_style` test suite expanded
Fixes #86

Fix renderer alignment bug when changing style range.

---

pybleau/app/io/legacy_deserializer.py

In some cases, this legacy deserializer is invoked but doesn't have an axis_name attribute.

Robustify the legacy AxisStyle deserializer.

---

pybleau/app/plotting/base_factories.py

Fixes https://github.com/KBIbiopharma/pybleau/issues/124

Fix/streamline renderer alignment method when only 1 renderer (heatmap).

---

pybleau/app/model/dataframe_plot_manager.py

The `_default_configs` dictionary in the `DataFramePlotManager` is needlessly private, and is not conducive to its needed use.

Make default_configs public

---

pybleau/app/ui/base_templates_list_dlg.py
pybleau/app/ui/tests/test_base_template_list_dlg.py

The `templates_exist` flag for the `Manage templates...` button was hindering discoverability of the full plot template feature, so it was removed. Additionally, it was the cause of a bug where the button was disabled even when templates existed. Disabling the button was deemed unnecessary.
Fixes KBIbiopharma/particle_data_viewer/issues/734

Remove check for template manage button

---

.coveragerc
.travis.yml
appveyor.yml
ci/pip_requirements.json
etstool.py

Switching to pytest for running the test suite to allow:
- coverage report generation in XML and HTML
- test duration computation
- unittest's search is finicky, relying on `__init__` files inside test sub-packages.

Maint: switch to pytest for running tests

---

pybleau/app/io/serializer.py
pybleau/app/io/tests/test_analyzer_roundtrip.py
pybleau/app/model/dataframe_analyzer.py
pybleau/app/model/tests/base_dataframe_analyzer.py
pybleau/app/model/tests/test_dataframe_analyzer.py
pybleau/app/model/tests/test_multi_df_dataframe_analyzer.py

- Adds a dict called `column_descr` to the analyzer to store free form column notes/descriptions.
- Keys added must be a column of the `source_df` or the entry will be removed.
Unrelated: added an assertion in the DFanalyzer tests to make sure that `uuid`s don't get lost during serialization.

Feature: add dict to store column notes/descriptions

---

pybleau/app/model/multi_dfs_dataframe_analyzer.py
pybleau/app/model/tests/test_multi_df_dataframe_analyzer.py

Support adding multiple columns to the `source_df` with a new `concat_to_source_df`. Only defined in the `MultiDfsAnalyzer`, at least for now.

Enh: source df management

---

etstool.py

By default, only request the 10 slowest test durations rather than all of them to reduce the output of a `etstool.py test` run.

Reduce default etstool test output.

---

etstool.py
pybleau/app/model/multi_dfs_dataframe_analyzer.py
pybleau/app/model/tests/test_multi_df_dataframe_analyzer.py

1. Improve how reindexing is done: `pd.merge` is replaced by `pd.reindex` which is faster and clearer.
2. Improve handling of overlapping columns by adding a suffix.

Improve concatenating DF

---

pybleau/app/model/multi_dfs_dataframe_analyzer.py
pybleau/app/ui/filter_expression_editor.py
pybleau/app/utils/button_list_view.py

Added a generic version of the `ScrollableButtonListView` called `ButtonListView` that does not implicitly allow scrolling. Also generalized the orientation ("horizontal" or "vertical")

Create a generic version of the ScrollableButtonListView

---

pybleau/app/model/dataframe_plot_manager.py
pybleau/app/model/tests/test_dataframe_plot_manager.py
pybleau/app/plotting/base_factories.py
pybleau/app/plotting/multi_mapper_plot.py
pybleau/app/plotting/plot_style.py
pybleau/app/plotting/tests/test_dataframe_plot_factories.py
pybleau/app/plotting/tests/test_multi_mapper_plot.py

Add a new chaco plot base class similar to `Plot` from an attribute list perspective but flexible like an OverlayPlotContainer, so it supports multiple renderer mappers.

Add new base class for plots generated by PlotFactories.

---

pybleau/app/model/multi_dfs_dataframe_analyzer.py
pybleau/app/model/tests/test_multi_df_dataframe_analyzer.py

Adding another API function to work with the private attribute `_source_dfs`.
Will not merge until there is a clear need for this API method.

Add set_source_df_part method on MultiDataFrameAnalyzer.

---

pybleau/app/model/multi_dfs_dataframe_analyzer.py
pybleau/app/model/tests/test_multi_df_dataframe_analyzer.py

Fix set_source_df_col: always trigger the _source_dfs_changed event on set_source_df_col. Otherwise, changing a column won't trigger an update of the source and `filtered_df`.
Fixes https://github.com/KBIbiopharma/pybleau/issues/189

set_source_df_col triggers change event
